[package]
name = "socketpair"
version = "0.6.2-alpha.0"
description = "Cross-platform socketpair functionality"
authors = ["Dan Gohman <dev@sunfishcode.online>"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
keywords = ["io"]
categories = ["rust-patterns"]
repository = "https://github.com/sunfishcode/socketpair"

[build-dependencies]
rustc_version = "0.3.3"

[dependencies]
async-std = { version = "1.9.0", optional = true }
io-close = "0.3.3"
unsafe-io = "0.6.0"

[target.'cfg(not(windows))'.dependencies]
posish = "0.6.0"
libc = "0.2.82"

[target.'cfg(windows)'.dependencies]
uuid = { version = "0.8.1", features = ["v4"] }
winapi = { version = "0.3.9", features = ["handleapi", "namedpipeapi", "std", "winerror"] }

[dev-dependencies]
anyhow = "1.0.38"

[features]
default = []
use_async_std = ["async-std", "unsafe-io/async-std"]

[badges]
maintenance = { status = "actively-developed" }
