[package]
name = "socketpair"
version = "0.9.1"
description = "Cross-platform socketpair functionality"
authors = ["Dan Gohman <dev@sunfishcode.online>"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
keywords = ["io"]
categories = ["rust-patterns"]
repository = "https://github.com/sunfishcode/socketpair"
exclude = ["/.github"]

[build-dependencies]
rustc_version = "0.4.0"

[dependencies]
async-std = { version = "1.9.0", optional = true }
tokio = { version = "1.8.1", optional = true }
unsafe-io = "0.8.1"
io-lifetimes = { version = "0.2.3", default-features = false }

[target.'cfg(not(windows))'.dependencies]
rsix = "0.18.0"

[target.'cfg(windows)'.dependencies]
uuid = { version = "0.8.1", features = ["v4"] }
winapi = { version = "0.3.9", features = ["handleapi", "namedpipeapi", "std", "winerror"] }

[dev-dependencies]
anyhow = "1.0.38"

[features]
default = []
use_async_std = ["async-std", "unsafe-io/async-std", "io-lifetimes/async-std"]
use_tokio = ["tokio", "unsafe-io/tokio", "io-lifetimes/tokio"]

[badges]
maintenance = { status = "actively-developed" }
